### PR TITLE
komorebi: FHS compliant install locations

### PR DESCRIPTION
**Pull request by Kangie**
/System/Applications --> /usr/bin
/System/Resources --> /usr/share
/Komorebi --> komorebi

Icons now installed to /usr/share/pixmaps/komorebi/

Trailing slashes added to CMakeLists.txt for consistency in paths.

The postinst script will need to be looked at by someone that uses a debian-based system.

### CODE REVIEW

**Comment by Ev1lbl0w** [comment]
Should that be implemented in this PR also, or keep it for another separate one?

**Comment by FFY00** [comment]
I'd prefer it was implemented here. And I think it should be in the same commit.

**Comment by Kangie** [comment]
No worries. I'm happy to implement that fix into this branch before we merge. I'll get on it in the morning.

**Comment by Arham4** [comment]
Is there any update to this issue? (:

**Comment by Kangie** [comment]
Actually sat down to start on this a fortnight ago and got struck down by illness. It's on my to-do list, let's say early next week?

**Comment by Ev1lbl0w** [comment]
> Actually sat down to start on this a fortnight ago and got struck down by illness. It's on my to-do list, let's say early next week?

Don't worry, take all the time you need 🙂

**Pull request closed without merging**
