### PR TITLE
Allow file:// URI type

### LINKED ISSUE #6: Feature request : Local web page?
It would be nice if local web pages are supported, since Internet isn't always available.

### PR DESCRIPTION
**Pull request by Ev1lbl0w**
Fixes #6 

This should be further improved *(by e.g. having a file choose dialog)*, but for now fixes the issue.

### CODE REVIEW

**Comment by redbrain** [comment]
i'm not a reviewer/member but the code looks fine to me

**Comment by minhducsun2002** [comment]
This looks fine, a maintainer should merge it soon.

**Comment by Ev1lbl0w** [comment]
> The same concept, in my opinion, applies here. We should allow for only a whitelisted list of URI types (file:// for the issue at hand, as you said, http://, and https:// because yay security!). I don't see why we should allow for every type of URI scheme to be used.

I agree with you, and like I said on the issue, this need to be way more fleshed out. This was a quick and dirty solution to make it work, but now in retrospective, yeah, I did this in a rush and really shouldn't.

I was thinking of an optional checkbox next to the URI field with something like *`Save this website locally`*, but I don't know if there's a way to properly save a website using only GTK/WebKit, so it needs to be investigated.

Otherwise, we can just have a file chooser dialog to select a local `*.html` file. But then it can be confusing to the user, since he might think he needs to use a local file and can't use a `http` URL.

I'm open to suggestions of what would be the best UI/UX for this feature.

**Comment by Arham4** [comment]
My suggestion was really to still respect your decision to not do the UI
work for the issue but still to allow the expansion of the idea safely.

**Comment by redbrain** [comment]
In the initial dropdown you could replace "From a webpage" with a set of options, "From a website online" or "from a local html file," the latter having a file-picker dialog.

**Comment by Ev1lbl0w** [comment]
Sorry for the late reply, I've had some exams in the way.

> My suggestion was really to still respect your decision to not do the UI
work for the issue but still to allow the expansion of the idea safely.

Ah, alright I misinterpreted that :stuck_out_tongue: I'll make this feature more robust then, and then at some other time propose a good UI/UX

> In the initial dropdown you could replace "From a webpage" with a set of options, "From a website online" or "from a local html file," the latter having a file-picker dialog.

Your suggestion sparked me another idea: what if we just have two fields, `From a website` or `From local file`, such that both options accept images, videos and URLs, but one fetches them online and the other one offline?

**Comment by Arham4** [comment]
Sorry for the delay. I was wanting this ideally in some sort of an array, but this should suffice. (:

**Pull request merged**
